// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igndnzvlhtziaoqumsnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbmRuenZsaHR6aWFvcXVtc250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTM1ODAsImV4cCI6MjA2MDQ4OTU4MH0.61RtwLNhvsDEt6SYyl4XHOnuLthNB9h1apilQQPQOlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);